---
deployment:
  tasks:
<<<<<<< HEAD
    - export DEPLOYPATH=/home/roph7587/public_html/prod
    - /bin/cp -R * $DEPLOYPATH
||||||| merged common ancestors
    - export DEPLOYPATH=/home/roph7587/public_html/stage
    - /bin/cp -R * $DEPLOYPATH
=======
    - export DEPLOYPATH=/home/roph7587/public_html/prod
    - /bin/cp -R * $DEPLOYPATH
>>>>>>> 1196e63ce097d838148534930ded68d111efb455
